# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: DaCapo Benchmarks
description: The DaCapo Benchmark Suite
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://dacapobench.org" # the base hostname & protocol for your site, e.g. http://example.com
name: "DaCapo Benchmarks"
twitter_username: dacapobench
github_username:  dacapobench

# need to implement --- orcid_id: 0000-0001-6632-6001  # https://orcid.org/0000-0001-6632-6001

include: ["_pages"]

# Build settings
markdown: kramdown
# theme: minima
theme: minimal-mistakes-jekyll
#plugins:
#  - jekyll-feed

minimal_mistakes_skin : "contrast"
site.locale: "en-AU"

encoding: utf-8


defaults:
  # _pages
  - scope:
      path: ""
      type: pages
    values:
      layout: single
      author_profile: true

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
exclude:
    - images-src
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
